packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'example'
  # exclude packages that are inside test directories
  - '!**/test/**'